pipeline{
    stages{
    stage('Checkout'){
        steps{
            deleteDir()
            checkout scm
        }
    }

    stage('Run Test'){
        agent{
            docker{
                image 'python:3.12.1-alpine3.19'
            }
        stages {
            stage('build') {
                steps {
                    sh 'python --version'
                }
            }
        }
        }
    }
}
}
